export type NoteType = 'user' | 'ai' | 'warning' | 'insight' | 'suggestion';
export type NotePriority = 'low' | 'medium' | 'high' | 'critical';
export type NoteGenerationSource = 'task_analysis' | 'progress_review' | 'manual_request' | 'auto_warning';
export type NoteFilterType = 'all' | 'ai' | 'user' | 'warnings';

export interface AIMetadata {
  generatedFrom: NoteGenerationSource;
  confidence: number; // 0-1 score
  sourceContext: string;
  generatedAt: string;
}

export interface Note {
  id: string;
  content: string;
  type: NoteType;
  tags?: string[]; // For categorization
  relatedTaskIds?: string[]; // Direct connections to specific checklist items
  planId: string;
  createdAt: string;
  updatedAt: string;
  priority: NotePriority;
  aiMetadata?: AIMetadata;
  isRead?: boolean;
  isDismissed?: boolean;
}

export interface NotesState {
  notes: Note[];
  isGeneratingNote: boolean;
  selectedTags: string[];
  filterBy: NoteFilterType;
  activeNoteId: string | null;
}

export interface TaskNoteRelation {
  taskId: string;
  noteId: string;
  relationshipType: 'blocks' | 'depends_on' | 'inspired_by' | 'warns_about' | 'suggestion_for';
  strength: number; // 0-1 confidence score
}

export interface WarningNote extends Note {
  type: 'warning';
  severity: 'info' | 'warning' | 'critical';
  autoGenerated: boolean;
  dismissible: boolean;
  actionSuggestions: string[];
}

export interface CreateNoteRequest {
  content: string;
  type: NoteType;
  tags?: string[];
  relatedTaskIds?: string[];
  priority?: NotePriority;
}

export interface UpdateNoteRequest {
  content?: string;
  tags?: string[];
  priority?: NotePriority;
  isRead?: boolean;
  isDismissed?: boolean;
}